# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]

handlers:

- url: /(.*\.(js|map|css|png|JPG))$
  static_files: dist/gauramarg-ui/\1
  upload: dist/gauramarg-ui/.*\.(js|map|css|png|JPG)$

- url: .*
  static_files: dist/gauramarg-ui/index.html
  upload: dist/gauramarg-ui/index.html

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json



