/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddressComponent { 
    longName?: string;
    shortName?: string;
    types?: Array<AddressComponent.TypesEnum>;
}
export namespace AddressComponent {
    export type TypesEnum = 'street_address' | 'route' | 'intersection' | 'political' | 'country' | 'administrative_area_level_1' | 'administrative_area_level_2' | 'administrative_area_level_3' | 'administrative_area_level_4' | 'administrative_area_level_5' | 'colloquial_area' | 'locality' | 'ward' | 'sublocality' | 'sublocality_level_1' | 'sublocality_level_2' | 'sublocality_level_3' | 'sublocality_level_4' | 'sublocality_level_5' | 'neighborhood' | 'premise' | 'subpremise' | 'postal_code' | 'postal_code_prefix' | 'postal_code_suffix' | 'natural_feature' | 'airport' | 'park' | 'point_of_interest' | 'floor' | 'establishment' | 'parking' | 'post_box' | 'postal_town' | 'room' | 'street_number' | 'bus_station' | 'train_station' | 'subway_station' | 'transit_station' | 'light_rail_station' | 'unknown';
    export const TypesEnum = {
        StreetAddress: 'street_address' as TypesEnum,
        Route: 'route' as TypesEnum,
        Intersection: 'intersection' as TypesEnum,
        Political: 'political' as TypesEnum,
        Country: 'country' as TypesEnum,
        AdministrativeAreaLevel1: 'administrative_area_level_1' as TypesEnum,
        AdministrativeAreaLevel2: 'administrative_area_level_2' as TypesEnum,
        AdministrativeAreaLevel3: 'administrative_area_level_3' as TypesEnum,
        AdministrativeAreaLevel4: 'administrative_area_level_4' as TypesEnum,
        AdministrativeAreaLevel5: 'administrative_area_level_5' as TypesEnum,
        ColloquialArea: 'colloquial_area' as TypesEnum,
        Locality: 'locality' as TypesEnum,
        Ward: 'ward' as TypesEnum,
        Sublocality: 'sublocality' as TypesEnum,
        SublocalityLevel1: 'sublocality_level_1' as TypesEnum,
        SublocalityLevel2: 'sublocality_level_2' as TypesEnum,
        SublocalityLevel3: 'sublocality_level_3' as TypesEnum,
        SublocalityLevel4: 'sublocality_level_4' as TypesEnum,
        SublocalityLevel5: 'sublocality_level_5' as TypesEnum,
        Neighborhood: 'neighborhood' as TypesEnum,
        Premise: 'premise' as TypesEnum,
        Subpremise: 'subpremise' as TypesEnum,
        PostalCode: 'postal_code' as TypesEnum,
        PostalCodePrefix: 'postal_code_prefix' as TypesEnum,
        PostalCodeSuffix: 'postal_code_suffix' as TypesEnum,
        NaturalFeature: 'natural_feature' as TypesEnum,
        Airport: 'airport' as TypesEnum,
        Park: 'park' as TypesEnum,
        PointOfInterest: 'point_of_interest' as TypesEnum,
        Floor: 'floor' as TypesEnum,
        Establishment: 'establishment' as TypesEnum,
        Parking: 'parking' as TypesEnum,
        PostBox: 'post_box' as TypesEnum,
        PostalTown: 'postal_town' as TypesEnum,
        Room: 'room' as TypesEnum,
        StreetNumber: 'street_number' as TypesEnum,
        BusStation: 'bus_station' as TypesEnum,
        TrainStation: 'train_station' as TypesEnum,
        SubwayStation: 'subway_station' as TypesEnum,
        TransitStation: 'transit_station' as TypesEnum,
        LightRailStation: 'light_rail_station' as TypesEnum,
        Unknown: 'unknown' as TypesEnum
    };
}


