/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Timestamp } from './timestamp';


export interface Holi { 
    address?: string;
    barCode?: string;
    city?: string;
    colorTaken?: number;
    comboTicket?: number;
    doorCode: string;
    email?: string;
    entered?: number;
    generalAdmission?: number;
    id?: string;
    modified?: Timestamp;
    name: string;
    paid?: string;
    parked?: number;
    phone?: string;
    postCode: string;
    premiumParking?: string;
    state?: string;
    ticketsPurchased?: string;
}

