/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Timestamp } from './timestamp';


export interface Payment { 
    amount?: number;
    courseId: string;
    id?: string;
    notes?: string;
    paymentTime?: Timestamp;
    paymentTimeString?: string;
    studentId: string;
    teacherId: string;
}

