/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { URL } from './uRL';


export interface Resource { 
    description?: string;
    file?: any;
    filename?: string;
    inputStream?: object;
    open?: boolean;
    readable?: boolean;
    uri?: string;
    url?: URL;
}

