/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Timestamp } from './timestamp';


export interface User { 
    created?: Timestamp;
    email?: string;
    firstName?: string;
    lastName?: string;
    modified?: Timestamp;
    password?: string;
    phone?: string;
    type?: User.TypeEnum;
}
export namespace User {
    export type TypeEnum = 'student' | 'teacher' | 'eventManager' | 'holiEventManager' | 'admin';
    export const TypeEnum = {
        Student: 'student' as TypeEnum,
        Teacher: 'teacher' as TypeEnum,
        EventManager: 'eventManager' as TypeEnum,
        HoliEventManager: 'holiEventManager' as TypeEnum,
        Admin: 'admin' as TypeEnum
    };
}


