export * from './address.service';
import { AddressService } from './address.service';
export * from './attendance.service';
import { AttendanceService } from './attendance.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './course.service';
import { CourseService } from './course.service';
export * from './courseRegistration.service';
import { CourseRegistrationService } from './courseRegistration.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './holi.service';
import { HoliService } from './holi.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AddressService, AttendanceService, AuthenticationService, CourseService, CourseRegistrationService, DashboardService, FileService, HoliService, PaymentService, UserService];
